<?php
declare(strict_types=1);

namespace QuantumAstrology\Reports;

use Mpdf\Mpdf;
use QuantumAstrology\Charts\Chart;
use RuntimeException;

class ReportGenerator
{
    private Mpdf $mpdf;

    public function __construct()
    {
        // Require ext-gd for mPDF image processing if needed
        $this->mpdf = new Mpdf([
            'mode' => 'utf-8',
            'format' => 'A4',
            'margin_left' => 15,
            'margin_right' => 15,
            'margin_top' => 16,
            'margin_bottom' => 16,
        ]);
    }

    /**
     * Generate a PDF report for a given chart.
     */
    public function generateNatalReport(int $chartId): string
    {
        $chartData = $this->loadChartData($chartId);
        
        $html = $this->renderTemplate($chartData);
        
        $this->mpdf->SetTitle('Astrological Analysis - ' . $chartData['name']);
        $this->mpdf->WriteHTML($html);
        
        return $this->mpdf->Output('', 'S'); // Return as string
    }

    private function loadChartData(int $chartId): array
    {
        $pdo = \QuantumAstrology\Core\DB::conn();
        $stmt = $pdo->prepare("SELECT * FROM charts WHERE id = :id");
        $stmt->execute([':id' => $chartId]);
        $row = $stmt->fetch();
        
        if (!$row) {
            throw new RuntimeException("Chart not found.");
        }
        
        return $row;
    }

    private function renderTemplate(array $data): string
    {
        // Basic template
        $name = htmlspecialchars($data['name']);
        $date = htmlspecialchars($data['birth_datetime']);
        
        return "
            <div style='font-family: sans-serif;'>
                <h1 style='color: #4A90E2;'>Quantum Astrology Report</h1>
                <h2>Natal Analysis for $name</h2>
                <p><strong>Birth Date:</strong> $date</p>
                <hr>
                <p>This report contains a detailed breakdown of your cosmic blueprint.</p>
                <div style='background: #f0f0f0; padding: 1rem; border-radius: 8px;'>
                    <p>Calculation Metadata: " . htmlspecialchars($data['calculation_metadata'] ?? '{}') . "</p>
                </div>
                <p style='margin-top: 2rem; font-size: 0.8rem; color: #666;'>
                    Generated by Quantum Minds United AI Engine.
                </p>
            </div>
        ";
    }
}
